# Generated by Django 3.1.4 on 2020-12-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=1000)),
                ('category_description', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anonymous', max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('topic', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('link', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=1000)),
                ('user_group_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_created', models.DateTimeField(editable=False)),
                ('post_content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(blank=True, default=0, editable=False, help_text='status id')),
                ('status_name', models.CharField(help_text='status name', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadForum',
            fields=[
                ('Thread_forum_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Thread_forum_subject', models.CharField(max_length=1000)),
                ('Thread_forum_created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=1000)),
                ('user_email', models.CharField(max_length=50)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(blank=True, default=0, editable=False)),
                ('status_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vote_up_count', models.IntegerField(blank=True, null=True)),
                ('vote_down_count', models.IntegerField(blank=True, null=True)),
                ('vote_post_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.post')),
                ('vote_thread_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.threadforum')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.group')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.userstatus'),
        ),
        migrations.AddField(
            model_name='threadforum',
            name='Thread_forum_user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.user'),
        ),
        migrations.AddField(
            model_name='threadforum',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.status'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_thread_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.threadforum'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.status'),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss', models.CharField(max_length=1000)),
                ('forum', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.forum')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.user'),
        ),
        migrations.AddField(
            model_name='category',
            name='status_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.status'),
        ),
    ]
