# Generated by Django 3.1.4 on 2020-12-29 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadforum',
            name='Thread_forum_created',
            field=models.DateTimeField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='threadforum',
            name='Thread_forum_id',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='threadforum',
            name='Thread_forum_subject',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='threadforum',
            name='Thread_forum_user_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.user'),
        ),
        migrations.AlterField(
            model_name='threadforum',
            name='status',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.status'),
        ),
    ]
