# Generated by Django 3.1.4 on 2021-01-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0003_auto_20201229_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadforum',
            name='Thread_forum_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
